import json
import os 


def serialize_schema(db_schema):
    """
    Converst a database schema dictionary into a string for TS.
    Format: | table1: col1, col2 | table2 : col2 ...
    """
    
    text_parts = []
    
    # create a map of table_id -> table name 
    
    table_names = db_schema['table_names_original']
    column_names = db_schema['column_names_original']
    
    # group columns by table 
    
    table_to_cols = {i: [] for i in range(len(table_names))}
    for col_idx, (table_idx, col_name) in enumerate(column_names):
        if table_idx >=0: # -1 is for special tokens like *
            table_to_cols[table_idx].append(col_name)
    
    # build the string 
    
    for table_idx, table_name in enumerate(table_names):
        cols = table_to_cols[table_idx]
        col_str = " , ".join(cols)
        text_parts.append(f"{table_name} : {col_str}")
    
    
    return " | ".join(text_parts)


def main():
    
    # 1. Load the data generated by the NATSQL shell script found in the NatSQL_v1_6 repo.
    
    print("Loading NatSQL formatted(preproccessed) data...")
    
    with open('NatSQLv1_6/train_spider.json', 'r') as f:
            train_data = json.load(f)

    with open('data/tables.json', 'r') as f:
            tables = json.load(f)


    db_schemas = {t['db_id']: t for t in tables}
        
    final_data = []

    print(f"Formatting {len(train_data)} examples...")
    
    for item in train_data:
        # The shell script adds a 'NatSQL' field to the JSON
        if 'NatSQL' not in item:
            continue # Skip if conversion failed for this item
            
        question = item['question']
        natsql = item['NatSQL'] # The simplified SQL
        db_id = item['db_id']
        
        # Format Schema
        schema_text = serialize_schema(db_schemas[db_id])
        
        # Create T5 Pair
        final_data.append({
            "source": f"Translate to NatSQL: {question} | {db_id} | {schema_text}",
            "target": natsql,
            "schema_serialization": schema_text, # Keep for safety
            "question": question,
            "natsql": natsql
        })


    # Save the clean file for Colab
    with open('ready_to_train.json', 'w') as f:
        json.dump(final_data, f, indent=2)
    
    print(f"Success! Saved {len(final_data)} items to 'ready_to_train.json'.")

if __name__ == "__main__":
    main()
    